### ISSUE TITLE
Guidence for customzining highlighting

### ISSUE THREAD

**Issue by shot-codes** [p00f/alabaster.nvim#7]
I'm looking at trying to change some highlight groups for rust. I'm pretty ignorant as to how nvim theming works but it looks like the the .scm files in after/queries map token types to color definitions (i.e. @AlalbasterDefininition). I've tried changing some of the values to @AlabasterConstant but don't see any changes.

Any guidance would be much appreciated

**Comment by p00f** [comment]
If you want to change the colours of `@AlabasterDefinition`, you can use
`hi! @AlabasterDefinition fg=#xxxxxxx bg=#xxxxxx` or the lua version ie `vim.api.nvim_set_hl()` - see `:h :highlight` and `:h nvim_set_hl()`, do one of these _after_ setting the colorscheme.


If you want to change the mapping (like highlighting struct names with `@AlabasterConstant` instead of `@AlabasterDefinition`) you'll have to change the queries (.scm files). This is more involved - see `:h treesitter-query`. `:h :InspectTree` is also very helpful when writing queries

**Comment by shot-codes** [comment]
Appreciate the reply, the latter is indeed what I am trying to do.

**Comment by p00f** [comment]
In this case you should just fork the repo IMO - it becomes a different theme when you do that

**Comment by shot-codes** [comment]
yeah I already did that to remove the background colors ;)

**Comment by shot-codes** [comment]
Really appreciate the theme btw. Ever since stumbling across the the original sublime theme from Tonsky, reading the motivation and giving it a spin, I've been completely sold. Even went so far as to make a vscode theme as I wasn't satisfied with the existing ones (https://marketplace.visualstudio.com/items?itemName=NicolaiVerbaarschot.alabaster-variant-theme).

But you helped me move to Neovim (with much less pain), and I am grateful for that <3
